version: '2'
services:
  php:
    image: yiisoftware/yii2-php:7.4-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'
    networks:
        - app-network

  db:
    image: mysql:8
    container_name: db_test_yii2
    restart: always
    environment:
      MYSQL_DATABASE: todo
      MYSQL_USER: davlat
      MYSQL_PASSWORD: qwe1234
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - ./tmp/db:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
